site_name: C# - Så funkar det
site_url: https://www.suvnet.se/
theme:
  features:
    - navigation.sections
    - navigation.instant
    - navigation.footer
  name: material
  logo: assets/logo.png
  repo_url: https://github.com/squidfunk/mkdocs-material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
